---
title: "Visualizing TBDBr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualizing TBDBr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(TBDBr)
#library(networkD3)
library(sunburstR)
library(htmltools)
library(d3r)
library(rlist)
library(data.tree)
library(sunburstR)
library(dplyr)
devtools::load_all()

tree <- getPathTrees()
tree <- tree$respMsg
collections <- list.names(tree)
tree <- unlist(tree, recursive = F)
names(tree) = collections
tree = as.Node(tree)
tree = ToDataFrameTypeCol(tree)
tree <- tree %>%
    mutate(level1 = level_2,
           level2 = level_3,
           level3 = level_4,
           level4 = level_5,
           level5 = level_6,
           level6 = level_7,
           level7 = level_8
    ) %>%
    select(level1:level7) %>%
    mutate(size = 1)
tree2 <- d3_nest(tree, value_cols = "size")
```

```{r, fig.height=8,fig.width=10,fig.align='left', echo=F}
sund2b(tree2)
```

